PLOTLY

In [2]:
pip install plotly

Requirement already satisfied: plotly in c:\users\sanab\appdata\local\programs\python\python312\lib\site-packages (7.0.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\sanab\appdata\local\programs\python\python312\lib\site-packages (from plotly) (2.25.0)
Requirement already satisfied: packaging in c:\users\sanab\appdata\roaming\python\python312\site-packages (from plotly) (26.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import plotly.express as px

In [4]:
import seaborn as sns
flight=sns.load_dataset('flights')
flight

     year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
..    ...   ...         ...
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

[144 rows x 3 columns]

In [5]:
monthly_pass=flight.groupby('month').agg({'passengers':'sum'}).reset_index()
monthly_pass

   month  passengers
0    Jan        2901
1    Feb        2820
2    Mar        3242
3    Apr        3205
4    May        3262
5    Jun        3740
6    Jul        4216
7    Aug        4213
8    Sep        3629
9    Oct        3199
10   Nov        2794
11   Dec        3142

In [7]:
import plotly.express as px
px.line(monthly_pass,x='month',y='passengers')

In [9]:
tip=px.data.tips()
tip

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [17]:
px.bar(tip,x='sex',y='total_bill',color='smoker')

In [18]:
px.bar(tip,x='sex',y='total_bill',color='smoker',barmode='group')
#barmode bbars different krdeta

In [ ]:
#pip install statsmodels #cmd

In [20]:
iris=px.data.iris()
iris

,sepal_length,sepal_width,petal_length,petal_width,species,species_id
0,5.1,3.5,1.4,0.2,setosa,1
1,4.9,3.0,1.4,0.2,setosa,1
2,4.7,3.2,1.3,0.2,setosa,1
3,4.6,3.1,1.5,0.2,setosa,1
4,5.0,3.6,1.4,0.2,setosa,1
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,3
146,6.3,2.5,5.0,1.9,virginica,3
147,6.5,3.0,5.2,2.0,virginica,3
148,6.2,3.4,5.4,2.3,virginica,3
149,5.9,3.0,5.1,1.8,virginica,3

In [24]:
px.scatter(iris,x='sepal_length',y='sepal_width',color='species')

In [26]:
px.scatter(iris,x='sepal_length',y='sepal_width',color='species',trendline='ols')
#trendline trend dikha deti hai linear line method
#ols=ordinary least square

In [29]:
gap=px.data.gapminder()
gap

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4
...,...,...,...,...,...,...,...,...
1699,Zimbabwe,Africa,1987,62.351,9216418,706.157306,ZWE,716
1700,Zimbabwe,Africa,1992,60.377,10704340,693.420786,ZWE,716
1701,Zimbabwe,Africa,1997,46.809,11404948,792.449960,ZWE,716
1702,Zimbabwe,Africa,2002,39.989,11926563,672.038623,ZWE,716
1703,Zimbabwe,Africa,2007,43.487,12311143,469.709298,ZWE,716

In [31]:
px.scatter(gap,x='pop',y='lifeExp')

In [36]:
px.scatter(gap,x='pop',y='lifeExp',log_x=True,log_y=True,animation_frame='year',color='continent',hover_name='country')

7.0.0
['scatter', 'scatter_3d', 'scatter_geo', 'scatter_map', 'scatter_matrix', 'scatter_polar', 'scatter_ternary']